### PR TITLE
Add more baseline layouts

### PR DESCRIPTION
**Pull request by chingjun**
Add keepFirstBaselineInset, keepLastBaselineInset, keepFirstBaselineOffsetTo, keepLastBaselineOffsetTo

### CODE REVIEW

**Comment by Tricertops** [comment]
Thank you for your pull request. I will review it later today.

**Comment by K-Be** [comment]
It is a useful feature, but I think this feature is not completed. Often we need create vertical space between two labels (from last base line to first base line).

**Comment by chingjun** [comment]
@K-Be If you look into the PR you can see that `keepFirstBaselineOffsetTo` does exactly what you mentioned.

Since we're at it, should we add `keepFirstBaselineAlignTo` and `keepLastBaselineAlignTo` for the sake of completeness? We haven't used these in our codebase so I didn't add them in the PR.

The other four that was mentioned in the PR however, were used intensively in our code base for about a year now :)

**Comment by K-Be** [comment]
keepFirstBaselineOffsetTo uses UIView* as a parameter, I can't indicate that I want to use firstBaseLine if the related view as the parameter. 

Sorry but I can't find how I can implement analog of the constraint: 
```
UILabel* name;
UILabel* secondName;
NSLayoutConstraint* constraint = [NSLayoutConstraint constraintWithItem:name attribute:NSLayoutAttributeLastBaseline relatedBy:NSLayoutRelationEqual toItem:secondName attribute:NSLayoutAttributeFirstBaseline multiplier:1.0 constant:20.0];
```
image

**Comment by K-Be** [comment]
May be #72 is useful here.

**Comment by chingjun** [comment]
It can be achieved by `secondName.keepFirstBaselineOffsetTo(name).equal = 20` or `name.keepLastBaselineOffsetTo(secondName).equal = 20`

If one of the views is a `UIView *`, auto layout will automatically uses "bottom" as the view's "last baseline"

However, I can't achieve `name.bottom + 20 == secondName.firstBaseline` in the current API. Even when name is not a `UILabel`.

I think that is acceptable as it's not as common as the use case you mentioned. Also KeepLayout has its own limitation, just as I couldn't achieve `image.centerY == view.bottom` in KeepLayout. (Please correct me if I'm wrong, that's one of the few cases where I had to fallback to the tedious NSLayoutConstraint API)

**Comment by Tricertops** [comment]
Hi, I’m sorry, I forgot about this PR 😅

I just merged it with some little clarification in comments.

@chingjun Even if KeepLayout cannot directly produce constraints for arbitrary pair of layout attributes, it is possible to achieve desired layout embedding in helper UIViews. My goal was to cover 90% use cases with much simpler syntax. Your example `name.bottom + 20 == secondName.firstBaseline` can be achieved in only by embedding the `secondName` in a UIView and setting these:

```objc
secondName.keepLastBaselineInset.equal = 0
name.keepBottomAlignTo(secondName.superview).equal = 20
```

@K-Be Offset attributes always use **opposite edge** of the other view: left with right edge, top with bottom edge, first with last baseline. Alignment attributes always use **the same edge** of both views: left with left edge, top with top edge, first with first baseline. That’s why `.keepLastBaselineOffsetTo()` keeps distance to first baseline of the other view.

**Comment by Tricertops** [comment]
@chingjun I’m thinking about your another example `image.centerY == view.bottom`. I have an idea with using helper view with half size of the image.

```objc
let helper = UIView()
view.addSubview(helper)

helper.keepBottomInset.equal = 0
helper.keepHeightEqualTo(image).equal = 0.5
helper.keepTopAlignTo(image).equal = 0

// That’s just Y axis, handle X as you wish.
```

**Comment by chingjun** [comment]
> @chingjun Even if KeepLayout cannot directly produce constraints for arbitrary pair of layout attributes, it is possible to achieve desired layout embedding in helper UIViews. My goal was to cover 90% use cases with much simpler syntax.

Totally agree with this!

> @chingjun I’m thinking about your another example image.centerY == view.bottom. I have an idea with using helper view with half size of the image.

While it does achieve the same result, I doubt that any other maintainers can understand my intention in this case. This isn't used as often as the other cases, I'm in favor of code clarity in this case.

And thanks for accepting the PR :)

**Comment by Tricertops** [comment]
I also implemented NSArray baseline attributes with one new convenience method to offset several views at once:

```swift
let labels: [UIView] = [labelA, labelB, labelC, labelD]
labels.keepBaselineOffsets(20)
```

**Pull request merged**
